# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WCHBLEOTA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WCHBLEOTA

  pod 'MBProgressHUD' #https://github.com/jdg/MBProgressHUD
  pod 'SnapKit'       #Autolayout DSL https://github.com/SnapKit/SnapKit
  pod 'XCGLogger'
  pod 'MJRefresh'

end
